server:
  port: 80

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: be713592-842b-4885-9251-9fd0f3d0f770
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-server
          uri: lb://gateway-server
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /doc.html

        - id: game-third-server
          uri: lb://game-third-server
          predicates:
            - Path=/third/**
          filters:
            - StripPrefix=1

        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: box-app-server
          uri: lb://box-app-server
          predicates:
            - Path=/box/**
          filters:
            - StripPrefix=1

        - id: scheduler-server
          uri: lb://scheduler-server
          predicates:
            - Path=/sched/**
          filters:
            - StripPrefix=1

        - id: socket-server
          uri: lb://socket-server
          predicates:
            - Path=/sk/**
          filters:
            - StripPrefix=1

#springdoc:
#  api-docs:
#    path: /api-docs
#  webjars:
#    prefix:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    urls:
#      - name: 1.游戏服务接口
#        url: /box/api-docs
#      - name: 2.第三方服务接口
#        url: /third/api-docs
#      - name: 3.后台管理服务接口
#        url: /admin/api-docs
#      - name: 4.调度任务服务接口
#        url: /sched/api-docs

knife4j:
  gateway:
    enabled: true
    routes:
      - name: 1.游戏服务接口
        url: /box/api-docs
        service-name: box-app-server
        context-path: /box
      - name: 2.第三方服务接口
        url: /third/api-docs
        service-name: game-third-server
        context-path: /third
      - name: 3.后台管理服务接口
        url: /admin/api-docs
        service-name: admin-server
        context-path: /admin
      - name: 4.调度任务服务接口
        url: /sched/api-docs
        service-name: scheduler-server
        context-path: /sched
      - name: 5.socket服务接口
        url: /sk/api-docs
        service-name: scheduler-server
        context-path: /sk

