server:
  port: 80

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: be713592-842b-4885-9251-9fd0f3d0f770
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: game-third-server
          uri: lb://game-third-server
          predicates:
            - Path=/third/**
          filters:
            - StripPrefix=1

        - id: box-app-server
          uri: lb://box-app-server
          predicates:
            - Path=/**


springdoc:
  api-docs:
    path: /api-doc
  webjars:
    prefix:
  swagger-ui:
    path: /doc.html
    urls:
      - name: 第三方服务
        url: /third/api-docs
      - name: 盲盒服务
        url: /api-docs

