server:
  port: 0

spring:
  application:
    name: socket-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: be713592-842b-4885-9251-9fd0f3d0f770

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc
    url: /v3/api-docs