server:
  port: 0

spring:
  application:
    name: box-app-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: be713592-842b-4885-9251-9fd0f3d0f770
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gbb?characterEncoding=utf-8&useInformationSchema=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      password: 123321
      timeout: 3000 # 读超时
      connectTimeout: 5000 # 连接超时
      lettuce:  # Lettuce连接池
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000


springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /doc